<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260911114423 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE business (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, active_for_demo BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_menu_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D36E389FAD87E2 ON business (published_menu_id)');
        $this->addSql('CREATE TABLE call_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_call_id VARCHAR(120) NOT NULL, status VARCHAR(20) DEFAULT \'en curso\' NOT NULL, from_number VARCHAR(40) DEFAULT NULL, to_number VARCHAR(40) DEFAULT NULL, simulated BOOLEAN DEFAULT false NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration_seconds INT DEFAULT NULL, transcript TEXT DEFAULT NULL, business_id INT NOT NULL, menu_version_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_provider_call_id ON call_record (provider_call_id)');
        $this->addSql('CREATE INDEX IDX_5EEC4EB3A89DB457 ON call_record (business_id)');
        $this->addSql('CREATE INDEX IDX_5EEC4EB36A1193D7 ON call_record (menu_version_id)');
        $this->addSql('CREATE TABLE customer_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(12) NOT NULL, customer_name VARCHAR(120) DEFAULT NULL, fulfillment VARCHAR(20) DEFAULT NULL, notes TEXT DEFAULT NULL, total NUMERIC(10, 2) DEFAULT NULL, seen BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, business_id INT NOT NULL, call_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_order_call ON customer_order (call_id)');
        $this->addSql('CREATE INDEX IDX_3B1CE6A3A89DB457 ON customer_order (business_id)');
        $this->addSql('CREATE TABLE menu_import (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_type VARCHAR(20) NOT NULL, source_files JSON DEFAULT \'[]\' NOT NULL, source_text TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'pendiente\' NOT NULL, error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, business_id INT NOT NULL, menu_version_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4E0996C5A89DB457 ON menu_import (business_id)');
        $this->addSql('CREATE INDEX IDX_4E0996C56A1193D7 ON menu_import (menu_version_id)');
        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, category VARCHAR(120) DEFAULT NULL, description TEXT DEFAULT NULL, options JSON DEFAULT \'[]\' NOT NULL, price NUMERIC(8, 2) DEFAULT NULL, price_text VARCHAR(80) DEFAULT NULL, source_ref VARCHAR(120) DEFAULT NULL, needs_review BOOLEAN DEFAULT false NOT NULL, position INT DEFAULT 0 NOT NULL, menu_version_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D754D5506A1193D7 ON menu_item (menu_version_id)');
        $this->addSql('CREATE TABLE menu_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, published BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, business_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_37C7CE7DA89DB457 ON menu_version (business_id)');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_copy VARCHAR(200) NOT NULL, quantity INT NOT NULL, modifications TEXT DEFAULT NULL, unit_price NUMERIC(8, 2) DEFAULT NULL, order_id INT NOT NULL, menu_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52EA1F098D9F6D38 ON order_item (order_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F099AB44FE0 ON order_item (menu_item_id)');
        $this->addSql('CREATE TABLE webhook_receipt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_key VARCHAR(190) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_webhook_event ON webhook_receipt (event_key)');
        $this->addSql('ALTER TABLE business ADD CONSTRAINT FK_8D36E389FAD87E2 FOREIGN KEY (published_menu_id) REFERENCES menu_version (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_record ADD CONSTRAINT FK_5EEC4EB3A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_record ADD CONSTRAINT FK_5EEC4EB36A1193D7 FOREIGN KEY (menu_version_id) REFERENCES menu_version (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_order ADD CONSTRAINT FK_3B1CE6A3A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_order ADD CONSTRAINT FK_3B1CE6A350A89B2C FOREIGN KEY (call_id) REFERENCES call_record (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_import ADD CONSTRAINT FK_4E0996C5A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_import ADD CONSTRAINT FK_4E0996C56A1193D7 FOREIGN KEY (menu_version_id) REFERENCES menu_version (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D5506A1193D7 FOREIGN KEY (menu_version_id) REFERENCES menu_version (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_version ADD CONSTRAINT FK_37C7CE7DA89DB457 FOREIGN KEY (business_id) REFERENCES business (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES customer_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F099AB44FE0 FOREIGN KEY (menu_item_id) REFERENCES menu_item (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE business DROP CONSTRAINT FK_8D36E389FAD87E2');
        $this->addSql('ALTER TABLE call_record DROP CONSTRAINT FK_5EEC4EB3A89DB457');
        $this->addSql('ALTER TABLE call_record DROP CONSTRAINT FK_5EEC4EB36A1193D7');
        $this->addSql('ALTER TABLE customer_order DROP CONSTRAINT FK_3B1CE6A3A89DB457');
        $this->addSql('ALTER TABLE customer_order DROP CONSTRAINT FK_3B1CE6A350A89B2C');
        $this->addSql('ALTER TABLE menu_import DROP CONSTRAINT FK_4E0996C5A89DB457');
        $this->addSql('ALTER TABLE menu_import DROP CONSTRAINT FK_4E0996C56A1193D7');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D5506A1193D7');
        $this->addSql('ALTER TABLE menu_version DROP CONSTRAINT FK_37C7CE7DA89DB457');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F098D9F6D38');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F099AB44FE0');
        $this->addSql('DROP TABLE business');
        $this->addSql('DROP TABLE call_record');
        $this->addSql('DROP TABLE customer_order');
        $this->addSql('DROP TABLE menu_import');
        $this->addSql('DROP TABLE menu_item');
        $this->addSql('DROP TABLE menu_version');
        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE webhook_receipt');
    }
}
